Send emails when someone registers a new team
EagleScoutDev/EagleScout pull request #43
Opened 2024-03-12 17:33 UTC by alaninnovates

2024-03-12 17:50 UTC, gaborszita requested changes
Looks good overall 👍

2024-03-12 17:50 UTC, gaborszita commented on supabase/functions/register-team-email-trigger/README.md
> +
You should note that the `EMAILS` environment variable should also be set to the emails it needs to send an email to

2024-04-02 16:04 UTC, gaborszita commented
@alaninnovates can we merge this?

2024-04-03 06:04 UTC, alaninnovates commented
The `org-registration-email-trigger` has not been tested yet and is not in prod yet.

2025-01-17 05:51 UTC, alaninnovates commented
This pull request will be resolved by #68

2025-01-17 05:52 UTC, closed without merging